# Generated by Django 4.2.30 on 2026-07-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('data_gasto', models.DateField(verbose_name='Data do Gasto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.categoriagasto', verbose_name='Categoria')),
                ('funcionario_vinculado', models.ForeignKey(blank=True, help_text='Preencha apenas se for um gasto direcionado a um funcionário específico (ex: EPI, Adiantamento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_vinculados', to='core.funcionario', verbose_name='Funcionário Referente (Opcional)')),
            ],
        ),
    ]
