# Generated by Django 4.2.30 on 2026-07-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social / Nome Fantasia')),
                ('cnpj', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'))),
                ('telefone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'))),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', django_cryptography.fields.encrypt(models.CharField(max_length=14, verbose_name='CPF'))),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('tipo_pagamento', models.CharField(choices=[('MENSALISTA', 'Mensalista'), ('DIARISTA', 'Diarista')], default='MENSALISTA', max_length=20, verbose_name='Tipo de Pagamento')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salário Base / Mensal')),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor da Diária')),
                ('telefone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'))),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Proprietário')),
            ],
            options={
                'unique_together': {('usuario', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('PRESENCA', 'Presença (Trabalhou)'), ('FALTA', 'Falta'), ('ATESTADO', 'Atestado Médico'), ('FOLGA', 'Folga')], default='PRESENCA', max_length=15, verbose_name='Tipo do Registro')),
                ('valor_diaria_aplicada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diária Aplicada (R$)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação / Detalhe do Atestado')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_trabalho', to='core.funcionario', verbose_name='Funcionário')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Recebido (R$)')),
                ('data_recebimento', models.DateField(verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='core.empresa', verbose_name='Cliente / Parceiro')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('data_gasto', models.DateField(verbose_name='Data do Gasto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.categoriagasto', verbose_name='Categoria')),
                ('funcionario_vinculado', models.ForeignKey(blank=True, help_text='Preencha apenas se for um gasto direcionado a um funcionário específico (ex: EPI, Adiantamento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_vinculados', to='core.funcionario', verbose_name='Funcionário Referente (Opcional)')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Adiantamento (R$)')),
                ('data', models.DateField(verbose_name='Data do Adiantamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (A descontar)'), ('DESCONTADO', 'Descontado (Pago)')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='core.funcionario', verbose_name='Funcionário')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
