# Generated by Django 4.2.30 on 2026-07-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='empresa_cliente',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
