# Generated by Django 4.2.30 on 2026-07-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social / Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Adiantamento (R$)')),
                ('data', models.DateField(verbose_name='Data do Adiantamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (A descontar)'), ('DESCONTADO', 'Descontado (Pago)')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='core.funcionario', verbose_name='Funcionário')),
            ],
        ),
    ]
