# Generated by Django 4.2.30 on 2026-07-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_adiantamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_pagamento',
            field=models.CharField(choices=[('MENSALISTA', 'Mensalista'), ('DIARISTA', 'Diarista')], default='MENSALISTA', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor da Diária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salário Base / Mensal'),
        ),
        migrations.CreateModel(
            name='RegistroTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('PRESENCA', 'Presença (Trabalhou)'), ('FALTA', 'Falta'), ('ATESTADO', 'Atestado Médico'), ('FOLGA', 'Folga')], default='PRESENCA', max_length=15, verbose_name='Tipo do Registro')),
                ('valor_diaria_aplicada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diária Aplicada (R$)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação / Detalhe do Atestado')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_trabalho', to='core.funcionario', verbose_name='Funcionário')),
            ],
        ),
    ]
