# Generated by Django 4.2.30 on 2026-07-17 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Retorno')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atestados/', verbose_name='Foto do Atestado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações / CID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados_medicos', to='core.funcionario', verbose_name='Funcionário')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Período')),
                ('data_fim', models.DateField(verbose_name='Data de Fim do Período')),
                ('dias_trabalhados', models.PositiveIntegerField(default=0, verbose_name='Dias Trabalhados (Diaristas)')),
                ('dias_falta', models.PositiveIntegerField(default=0, verbose_name='Dias de Falta (Mensalistas)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='core.funcionario', verbose_name='Funcionário')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
