# Generated by Django 4.2.30 on 2026-07-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_tipo_pagamento_funcionario_valor_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Recebido (R$)')),
                ('data_recebimento', models.DateField(verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='core.empresa', verbose_name='Cliente / Parceiro')),
            ],
        ),
    ]
