# Generated by Django 4.2.30 on 2026-07-17 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_atestado_apontamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='bonificacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bonificação (R$)'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='valor_horas_extras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Horas Extras (R$)'),
        ),
        migrations.CreateModel(
            name='FazendaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Fazenda / Cliente')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='fazenda_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='core.fazendacliente', verbose_name='Fazenda / Cliente'),
        ),
        migrations.AddField(
            model_name='receita',
            name='fazenda_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='core.fazendacliente', verbose_name='Fazenda / Cliente'),
        ),
    ]
