# Generated by Django 4.2.30 on 2026-07-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apontamento_bonificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adiantamento',
            name='apontamento_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_descontados', to='core.apontamento'),
        ),
    ]
